# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Version bump

on:
  workflow_dispatch:
    inputs:
      versionPart:
        description: 'Version bump part'
        required: true
        default: patch
        type: choice
        options:
        - patch
        - minor
        - major

  workflow_call:
    inputs:
      versionPart:
        description: 'Version bump part'
        required: true
        type: string
      projectDir:
        description: 'Project directory where the pyproject.toml is located'
        required: false
        type: string
        default: '.'

jobs:
  deploy:
    name: Version bump on release branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipx
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git checkout -b release
    - name: Bumpversion
      run: |
        set -e
        pipx run --spec git+https://github.com/bulv1ne/poetry-bumpversion poetry-bumpversion ${{ inputs.versionPart }} --project-dir ${{ inputs.projectDir }}
    - name: Git push
      run: |
        git push origin release --force
    - name: Create Pull Request
      uses: actions/github-script@v7
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: 'Release version',
            owner,
            repo,
            head: 'release',
            base: '${{ github.event.repository.default_branch }}',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });
